# Generated by Django 5.2 on 2025-04-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yemek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Yemek Adı')),
                ('icerikler', models.TextField(verbose_name='İçindekiler')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyatı')),
                ('tarihce', models.TextField(blank=True, null=True, verbose_name='Tarihçesi')),
            ],
        ),
    ]
