# Generated by Django 5.2 on 2025-04-14 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('konu_anlatimi', models.TextField(help_text='Yemeğin malzemeleri ve yapılışı gibi detaylı açıklama.')),
                ('mevzuat', models.TextField(blank=True, help_text='Yemeğin tarihçesi veya ilginç bilgileri.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Yemek için görsel (fotoğraf) yükleme alanı.', null=True, upload_to='meals/')),
                ('fiyat', models.DecimalField(decimal_places=2, help_text='Yemeğin eklenme anındaki fiyat bilgisi.', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meals.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Yemek',
        ),
    ]
