# Generated by Django 5.2 on 2025-04-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_category_order_meal_order_subcategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Kategori için görsel yükleme alanı.', null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Alt kategori için görsel yükleme alanı.', null=True, upload_to='subcategories/'),
        ),
    ]
