# Generated by Django 5.2 on 2025-04-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_category_image_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Alt kategori görseli (opsiyonel)', null=True, upload_to='subcategories/'),
        ),
    ]
