# Generated by Django 5.2 on 2025-04-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_alter_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Alt kategori için görsel yükleme alanı.', null=True, upload_to='subcategories/'),
        ),
    ]
