# Generated by Django 5.2 on 2025-04-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_subcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='meal_history_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='meals.meal')),
            ],
        ),
    ]
